networks:
  keycloak-network:
    external: true
  traefik-network:
    external: true
    
services:
  rag-frontend:
    build:
      context: ./frontend
    container_name: rag-frontend
    env_file:
      - ./frontend/.env.local
    networks:
      - traefik-network
      - keycloak-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rag-frontend.rule=Host(`rag.localhost.com`)"
      - "traefik.http.services.rag-frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.rag-frontend.entrypoints=websecure"
      - "traefik.http.routers.rag-frontend.service=rag-frontend"
      - "traefik.http.routers.rag-frontend.tls=true"
      - "traefik.http.routers.rag-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.rag-frontend.loadbalancer.passhostheader=true"
      - "traefik.http.routers.rag-frontend.middlewares=compresstraefik"
      - "traefik.http.middlewares.compresstraefik.compress=true"
      - "traefik.docker.network=traefik-network"
    extra_hosts:
      - "keycloak.localhost.com:host-gateway"

